.PHONY:clean
main:main.o add.o sub.o
	g++ -Wall -g main.o add.o sub.o	
main.o:main.c
	g++ -Wall -g -c main.c -o main.o	
add.o:add.c
	g++ -Wall -g -c add.c -o add.o	
sub.o:sub.c
	g++ -Wall -g -c sub.c -o sub.o	

clean:
	@echo "begin delete ..."
	rm -f main *.o
